name: Run testing
on:
  push:
    branches:
      - master
      - cidev
  workflow_dispatch:
jobs:
  test:
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: lte/*
          cache: npm
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm test
